services:
  postgres-course:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ead-course
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123